name: Manual Build

on:
    workflow_dispatch:
        inputs:
            branch:
                description: 'Branch to build'
                required: true
                default: 'feature/itunes'

jobs:
    build:
        strategy:
            matrix:
                platform: [Win32, x64]
        runs-on: windows-latest
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.branch }}
            - name: Add MSBuild to PATH
              uses: microsoft/setup-msbuild@v1.3.1
            - name: Build
              run: |
                  MSBuild.exe vcproject/qaac.sln /m /p:Configuration=Release /p:Platform=${{ matrix.platform }}
            - name: Create ZIP
              run: |
                  $platform = "${{ matrix.platform }}"
                  $outdir = "qaac-$platform"
                  New-Item -ItemType Directory -Path $outdir -Force
                  Get-ChildItem -Path vcproject -Recurse -Filter "*.exe" | Copy-Item -Destination $outdir
                  Compress-Archive -Path (Join-Path $outdir "*") -DestinationPath "qaac-$platform.zip"
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: qaac-${{ matrix.platform }}
                  path: qaac-${{ matrix.platform }}.zip
